apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-s3-pv
spec:
  # The storage capacity is ignored by the S3 CSI driver, but it's
  # required by the CSI spec. A nominal value is sufficient.
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  # The Access Mode must be ReadWriteMany, as S3 is shared storage.
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-sc
  csi:
    driver: s3.csi.aws.com
    volumeHandle: my-s3-pv-handle  # This must be unique per PV
    volumeAttributes:
      bucketName: "my-sql-bucket-1575" # Replace with your bucket name
      # Optional: specify the AWS region if different from the cluster
      region: "us-east-1"